services:
  #База данных
  postgres:
    image: 'postgres:latest'
    container_name: messenger-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_HOST_PORT}:${DB_CONTAINER_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 3

  #Миграции
  liquibase-migrations:
    image: liquibase/liquibase:4.29
    container_name: messenger_migrations
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://${DB_HOST_NAME}:${DB_CONTAINER_PORT}/${DB_NAME}
      - --username=${DB_USER}
      - --password=${DB_PASSWORD}
      - update
    volumes:
      - ./migrations:/changesets

volumes:
  postgres_data:

