spring:
  application:
    name: messenger
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    enabled: false
    change-log: classpath:migrations/master.xml

server:
  port: 8080

jwt:
  lifetime: 5m
  secret: ${JWT_SECRET}